## Importing and stacking over the DataSet for the period August 2022 - July 2023

In [1]:
# Import the dependencies
import pandas as pd
from pathlib import Path
import os

In [2]:
# Set up path to the files
data_csv = Path('DataSet/')

# Put all csv files into a list
all_csv = ['JC-202208-citibike-tripdata.csv',
          'JC-202209-citibike-tripdata.csv',
          'JC-202210-citibike-tripdata.csv',
          'JC-202211-citibike-tripdata.csv',
          'JC-202212-citibike-tripdata.csv',
          'JC-202301-citibike-tripdata.csv',
          'JC-202302-citibike-tripdata.csv',
          'JC-202303-citibike-tripdata.csv',
          'JC-202304-citibike-tripdata.csv',
          'JC-202305-citibike-tripdata.csv',
          'JC-202306-citibike-tripdata.csv',
          'JC-202307-citibike-tripdata.csv']

# Create a loop to read all csv files
dfs = []
for f in all_csv:
    full_path = os.path.join(data_csv,f)
    df = pd.read_csv(full_path)
    dfs.append(df)

In [3]:
# Concatenate the files into one file that shows data for the period 08.2022 - 07.2023
combined_df = pd.concat(dfs, ignore_index=True)

In [4]:
# Look through the file
combined_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,D68047AAA9A72501,classic_bike,2022-08-12 18:14:45,2022-08-12 18:21:23,Columbus Drive,JC014,Hamilton Park,JC009,40.718355,-74.038914,40.727596,-74.044247,member
1,E5B82A9F588A7650,classic_bike,2022-08-19 01:04:39,2022-08-19 01:14:10,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,8 St & Washington St,HB603,40.736982,-74.027781,40.745984,-74.028199,member
2,13D19CCBCC9D7B76,classic_bike,2022-08-19 18:13:45,2022-08-19 19:32:47,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,11 St & Washington St,HB502,40.736982,-74.027781,40.749985,-74.027150,member
3,AA0DBFF220DA98F6,classic_bike,2022-08-21 13:43:05,2022-08-21 13:53:13,Columbus Drive,JC014,Montgomery St,JC099,40.718355,-74.038914,40.719420,-74.050990,member
4,8F11D340492FCD32,electric_bike,2022-08-04 22:02:12,2022-08-04 22:21:31,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,Pershing Field,JC024,40.736982,-74.027781,40.742677,-74.051789,member

In [5]:
# Drop rows with missing values
df_cleaned = combined_df .dropna().copy()

In [6]:
df_cleaned.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,D68047AAA9A72501,classic_bike,2022-08-12 18:14:45,2022-08-12 18:21:23,Columbus Drive,JC014,Hamilton Park,JC009,40.718355,-74.038914,40.727596,-74.044247,member
1,E5B82A9F588A7650,classic_bike,2022-08-19 01:04:39,2022-08-19 01:14:10,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,8 St & Washington St,HB603,40.736982,-74.027781,40.745984,-74.028199,member
2,13D19CCBCC9D7B76,classic_bike,2022-08-19 18:13:45,2022-08-19 19:32:47,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,11 St & Washington St,HB502,40.736982,-74.027781,40.749985,-74.027150,member
3,AA0DBFF220DA98F6,classic_bike,2022-08-21 13:43:05,2022-08-21 13:53:13,Columbus Drive,JC014,Montgomery St,JC099,40.718355,-74.038914,40.719420,-74.050990,member
4,8F11D340492FCD32,electric_bike,2022-08-04 22:02:12,2022-08-04 22:21:31,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,Pershing Field,JC024,40.736982,-74.027781,40.742677,-74.051789,member

In [7]:
# Check the type of the columns
df_cleaned.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [8]:
# Convert 'started_at' and 'ended_at' to datetime type
df_cleaned['started_at'] = pd.to_datetime(df_cleaned['started_at'])
df_cleaned['ended_at'] = pd.to_datetime(df_cleaned['ended_at'])

In [9]:
df_cleaned.dtypes

ride_id                       object
rideable_type                 object
started_at            datetime64[ns]
ended_at              datetime64[ns]
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 object
dtype: object

In [10]:
# Export file as csv
df_cleaned.to_csv("file.csv", index = False, header = True)